from enum import StrEnum


class AssessmentState(StrEnum):
    MET = "MET"
    NOT_MET = "NOT_MET"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    NOT_ASSESSABLE = "NOT_ASSESSABLE"


class RunState(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    UPHELD = "UPHELD"
    DISMISSED = "DISMISSED"
    CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"


class EvidenceRelationship(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    NOT_RELEVANT = "NOT_RELEVANT"
    UNCERTAIN = "UNCERTAIN"
